### ISSUE TITLE
Retrieve embedded models with Filter endpoint

### ISSUE THREAD

**Issue by carsonclarke570** [carsonclarke570/lair-api#6]
The filter endpoint should also embedded any child models in the json response. Let's say `Child` has foreign key to `Parent`. When filtering a list of `Parent`s, each json object should look something like:

```
{
  "id": 109,
  "children" : [
    {
      "id: "20"
    }
  ]
}
```

**Comment by AlexMapley** [comment]
D0ubt

**Comment by carsonclarke570** [comment]
@AlexMapley ?? lol
